### ISSUE TITLE
Issues with setup and start scripts

### ISSUE THREAD

**Issue by mjgorman** [genzgd/Lampost-Mud#16]
README seems out of date. The lampost_setup.py and lampost_mud.py both seem to have some issues relating to imports. Seems like maybe there was a refactor done and they weren't updated?

Using master branch and running either of those scripts:

```
Traceback (most recent call last):
  File "lampost_setup.py", line 3, in <module>
    from lampost.util import logging
ModuleNotFoundError: No module named 'lampost'
```

**Comment by genzgd** [comment]
Yes, the readme is out of date.  At this point you also need the lampost_lib project:

https://github.com/genzgd/lampost_lib

You'll need that library somewhere in your library path.

Things are still in a bit of flux as I have been separating out pure framework code from MUD code (and looking at replacing Angular 1.x with React.js)  Thanks for looking, I'll try to update stuff over the next week or so.

**Comment by mjgorman** [comment]
Cool. Thanks for the info.
